### ISSUE TITLE
US 41 - Eu, como usuário, desejo me cadastrar no aplicativo para conseguir utiliza-lo.

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#101]
## Descrição da Issue
Usuário conseguir se cadastrar no aplicativo.
### Tasks: 
- [x] Criar tela de cadastro; 
- [x] Salvar dados do usuário no backend;
- [x] Integrar a tela do front com os métodos do backend.

### Critérios de aceitação

- [x] Usuário conseguir se cadastrar;
- [x] Dados do usuários ficarem salvos;
- [x] Seguir arquitetura;
- [ ] Todo grupo aprovar.
