### ISSUE TITLE
US 42 - Eu, como usuário, desejo visualizar meus dados, para ver minhas informações.

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#102]
## Descrição da Issue
Usuário conseguir visualizar e editar seus dados.
### Tasks: 
- [ ] Criar tela de perfil. 
- [ ] Requisitar os dados do usuário no backend;
- [ ] Integrar a tela do front com os métodos do backend.

### Critérios de aceitação

- [ ] Usuário conseguir visualizar perfil;
- [ ] Seguir arquitetura;
- [ ] Todo grupo aprovar.

**Comment by iurisevero** [comment]
Diagrama inicial da tela de perfil do usuário

![Dojo Flutter-User Page](https://user-images.githubusercontent.com/42645264/96049665-bc0ae280-0e4e-11eb-93e9-4a8fea437609.png)
