### ISSUE TITLE
US45 - Eu, como usuário, desejo logar no aplicativo para ter acesso a ele.

### ISSUE THREAD

**Issue by caiovfernandes** [UnBArqDsw/2020.1_G13_iGado#103]
## Descrição da Issue
Eu, como usuário, desejo logar no aplicativo para ter acesso à ele. Fazer a autenticação do usuário. 

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] FrontEnd - Página de Login
- [x] FrontEnd - Autenticação com Backend
- [x] BackEnd - Configuração AUTH JWT
- [x] BackEnd - Autenticação de usuário

### Critérios de aceitação
- [x] Login e autenticação funcionando corretamente.
