### ISSUE TITLE
Documentar fechamento da sprint 7 e abertura da sprint 8

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#105]
## Descrição da Issue
Documentar as atas de fechamento e abertura das sprints 7 e 8, respectivamente.
### Tasks: 
- [ ] Documentar sprint Review;
- [ ] Documentar Sprint Retrospective
- [ ] Documentar Planning Poker;
- [ ] Documentar Sprint Planning.

### Critérios de aceitação
- [ ] Todos os ritos documentos;
- [ ] Documento seguindo o padrão criado.
