### ISSUE TITLE
Refatorar Diagrama de Pacotes

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#106]
## Descrição da Issue
Corrigir erros do Diagrama de Componentes, apontados pela professora no feedback da entrega passada.

### Tasks: 
- [x] Conferir maior detalhamentos dos pacotes internos;
- [x] Estabelecer, pelo menos, os relacionamentos de dependência entre os pacotes;
- [ ] Organizar os pacotes por camadas, mantendo: View - Controller - Models. Camada de persistência
mais abaixo. Camada de utilidades, por exemplo, mais abaixo também. Relações de dependência das
camadas superiores para as camadas inferiores. O inverso deve ser evitado. 

### Critérios de aceitação
- [x] Problemas apontados no feedback resolvidos
- [x] Pelo menos 1 membro do grupo revisar o documento
