### ISSUE TITLE
Refatorar Diagrama de Classes

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#107]
## Descrição da Issue
Corrigir erros do Diagrama de Componentes, apontados pela professora no feedback da entrega passada.

### Tasks: 
- [x] Quase toda a parte comportamental está especificada com getters e setters. Faltam métodos mais
específicos acerca da parte comportamental das entidades;
- [x] Há relacionamentos, que parecem heranças, mas estão especificados com setas que não atendem
bem à notação de generalização da UML;
- [x] Há entidades que não contém atributos, na "herança". Sei que é possível herdar da super os
atributos. Mas, normalmente, as filhas têm atributos específicos. Dá uma olhadinha se realmente não há
propriedades específicas no nível das entidades filhas. Ok?
- [x] Há mistura de idiomas, sendo as entidades especificadas em inglês. Mas, as semânticas dos
relacionamentos de associação, por exemplo, especificadas em português.

### Critérios de aceitação
- [x] Problemas apontados no feedback resolvidos
- [x] Pelo menos 1 membro do grupo revisar o documento
