### ISSUE TITLE
Refatorar Diagrama de Componentes

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#108]
## Descrição da Issue
Corrigir erros do Diagrama de Componentes, apontados pela professora no feedback da entrega passada.

### Tasks: 
- [x] Evidenciar as relações de dependência, semânticas e portas dos conectores entre componentes arquiteturais de subsistemas diferentes;
- [x] Evidenciar as portas de forma adequada nos conectores entre componentes arquiteturais de mesmo subsistema
- [x] Evitar ficar reaproveitando conectores para especificar relacionamentos diferentes.

### Critérios de aceitação
- [x] Problemas apontados no feedback resolvidos
- [x] Pelo menos 1 membro do grupo revisar o documento
