### ISSUE TITLE
Refatorar Diagrama de Sequência

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#109]
## Descrição da Issue
Corrigir erros do Diagrama de Componentes, apontados pela professora no feedback da entrega passada.

### Tasks: 
- [x] Padronizar todos os métodos com verbos no infinitivo. Boa parte está. Mas, nem todos. Ok?
- [x] Passar o diagrama para o inglês
- [x] Manter todas as entidades sendo especificadas com nomes no singular. Percebi que a entidade
:Insumo está especificada como :Insumos

### Critérios de aceitação
- [x] Problemas apontados no feedback resolvidos
- [x] Pelo menos 1 membro do grupo revisar o documento
