### ISSUE TITLE
Refatorar Diagrama de Atividades

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#110]
## Descrição da Issue
Corrigir erros do Diagrama de Componentes, apontados pela professora no feedback da entrega passada.

### Tasks: 
- [x] Padronizar todas as atividades com verbos no infinitivo, pois essas atividades representam ações.
- [x] Passar o digrama para o inglês
- [x] Padronizar iniciais utilizadas nas atividades. Reparem que há momentos que são utilizadas todas as
iniciais em maiúsculo. Já há outros momentos, nos quais apenas a primeira inicial está em maiúsculo, e
as demais em minúsculo.
- [x] Nos gateways, precisam ficar especificadas as perguntas, deixam claro sobre o que se trata cada
momento de decisão ao longo do fluxo.

### Critérios de aceitação
- [x] Problemas apontados no feedback resolvidos
- [x] Pelo menos 1 membro do grupo revisar o documento
