### ISSUE TITLE
Refatorar Diagrama de Comunicação/Colaboração

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#111]
## Descrição da Issue
Corrigir erros do Diagrama de Componentes, apontados pela professora no feedback da entrega passada.

### Tasks: 
- [x] Padronizar todos os métodos com verbos no infinitivo, pois esse é o padrão predominante nos
modelos dinâmicos anteriores: Diagrama de Sequência & Diagrama de Atividades.
- [x] Passar diagrama para o inglês
- [x] Padronizar todos os métodos com terminador "()". Exemplo: "selecionarFazenda()" e não
"selecionaFazenda". Há outros vários casos.

### Critérios de aceitação
- [x] Problemas apontados no feedback resolvidos
- [x] Pelo menos 1 membro do grupo revisar o documento
