### ISSUE TITLE
Refatorar Diagrama de Estados

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#112]
## Descrição da Issue
Corrigir erros do Diagrama de Componentes, apontados pela professora no feedback da entrega passada.

### Tasks: 
- [x] Alguns estados não parecem bem estados, quando avaliamos os nomes conferidos aos mesmos. Por
exemplo: "Exibir o menu principal de acordo com o acesso do usuário" ou "Restringir o acesso ao
sistema" ou "Gerar relatório" ou "Relatório de bovinos" ou "Relatório de insumos" ou "Relatório geral
da fazenda". Há outros casos ainda. Corrigir esses estados.
- [x] Passar diagrama para o inglês

### Critérios de aceitação
- [x] Problemas apontados no feedback resolvidos
- [x] Pelo menos 1 membro do grupo revisar o documento

**Comment by iurisevero** [comment]
## Bovinos

![StatesDiagram-Bovino](https://user-images.githubusercontent.com/42645264/97017897-d9157480-1524-11eb-9086-e8c3467b464d.png)

## Relatório

![StatesDiagram-Relatório](https://user-images.githubusercontent.com/42645264/97017901-da46a180-1524-11eb-90ed-ee39f356e4cc.png)

## Cadastro

![StatesDiagram-Cadastro](https://user-images.githubusercontent.com/42645264/97017904-dadf3800-1524-11eb-9348-c091a1b1a885.png)
