### ISSUE TITLE
US46 - Eu, como desenvolvedor desejo aplicar padrões de projetos no Relatório para ter uma estruturação melhor na criação deles

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#113]
## Descrição da Issue
Implementar as funções necessárias para criar um relatório. Após a implementação é necessário documentar os padrões utilizados.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar rota de geração dos relatórios
- [x] Aplicar padrões discutidos pelo grupo que encaixariam nesse objeto
- [x] Documentar padrões adotados

### Critérios de aceitação
- [x] Deve ser possível criar um relatório
- [x] Os padrões de projeto devem ter sido aplicados corretamente
- [x] Documento inserido na Wiki
