### ISSUE TITLE
US48 - Eu, como desenvolvedor desejo aplicar padrões de projetos no Bovino para ter uma melhor estruturação na criação deles

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#114]
## Descrição da Issue
Implementar as funções necessárias para criar um bovino. Após a implementação é necessário documentar os padrões utilizados.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar rota de geração dos bovinos
- [x] Aplicar padrões discutidos pelo grupo que encaixariam nesse objeto
- [x] Documentar padrões adotados

### Critérios de aceitação
- [x] Deve ser possível criar um relatório
- [x] Os padrões de projeto devem ter sido aplicados corretamente
- [x] Documento inserido na wiki
