### ISSUE TITLE
Realizar Design Sprint

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#12]
## Descrição da Issue
Realizar um _Design Sprint_ para conceituar uma ideia principal em um espaço curto de tempo.  

### Tasks: 
- [x] Realizar _brainstorm_;
- [x] Elaborar mapa mental;
- [x] Elaborar _rich ricture_;
- [x] Elaborar protótipo;
- [x] Elaborar _storyboard_.

### Critérios de aceitação
- [x] Todos os métodos estejam de condizentes com o projeto;
- [x] Validar com todos os integrantes do grupo;

**Comment by sudjoao** [comment]
Storyboard feito por mim hoje, durante a reunião de design sprint
<img width="1439" alt="Screen Shot 2020-09-08 at 1 38 27 PM" src="https://user-images.githubusercontent.com/40740008/92504158-a283d480-f1d8-11ea-8224-d81980776ff6.png">

**Comment by ghost** [comment]
StoryBoard feito por mim hoje, durante a reunião de _design sprint_
<img width="1142" alt="Screen Shot 2020-09-02 at 8 54 04 AM" src="https://user-images.githubusercontent.com/40740008/91978075-e9b22700-ecf9-11ea-8220-9e802c9b6a33.png">

**Comment by iurisevero** [comment]
[StoryBoard_Desenho.pdf](https://github.com/UnBArqDsw/2020.1_G13_Projeto/files/5162075/StoryBoard_Desenho.pdf)

![StoryBoard_Desenho](https://user-images.githubusercontent.com/42645264/91978179-16fed500-ecfa-11ea-8171-457fffbd1757.png)

**Comment by guilherme-mendes** [comment]
![image](https://user-images.githubusercontent.com/37874689/91978740-0569fd00-ecfb-11ea-8af7-1aebda05ff3b.png)

**Comment by caiovfernandes** [comment]
![igabdo-highres](https://user-images.githubusercontent.com/42192251/91979623-69d98c00-ecfc-11ea-9b59-95a2a220a398.png)

**Comment by caiovfernandes** [comment]
<img width="868" alt="Screen Shot 2020-09-02 at 09 11 28" src="https://user-images.githubusercontent.com/42192251/91979673-7d84f280-ecfc-11ea-8616-adbecd37c28f.png">

**Comment by sudjoao** [comment]
Pull request aberto, aguardando aprovação.
