### ISSUE TITLE
Documentação dos padrões de projetos aplicados

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#123]
## Descrição da Issue
Documentar todos os padrões de projetos utilizados pelo grupo durante o desenvolvimento do software.

### Tasks: 
- [x] Documentar GRAP'S utilizados;
- [x] Documentar GoFs Criacionais;
- [x] Documentar GoFs Estruturais;
- [x] Documentar GoFs Comportamentais.
### Critérios de aceitação

- [x] Seguir bibliografia;
- [x] Todo grupo concordar.
