### ISSUE TITLE
Tela individual de bovino

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#130]
## Descrição da Issue
Elaborar a tela individual do Bovino no Front-end e integrar com o Back-end da aplicação.

### Tasks: 
- [x] Elaborar tela front-end;
- [x] Integrar com o back-end;

### Critérios de aceitação
- [x] Estar tudo funcionando;
- [x] Integração do back com o front sem erros;
