### ISSUE TITLE
Tela de criação de bovino

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#131]
## Descrição da Issue
Elaborar a tela de criação do Bovino no Front-end e integrar com o Back-end da aplicação.

### Tasks: 
- [x] Elaborar tela front-end;
- [x] Integrar com o back-end;

### Critérios de aceitação
- [x] Estar tudo funcionando;
- [x] Integração do back com o front sem erros;
