### ISSUE TITLE
Tela geral de bovino

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#132]
## Descrição da Issue
Criação da tela de visualização de todos os bovinos.
### Tasks: 
- [x] Criar rota para pegar todos os bovinos de uma determinada fazenda;
- [x] Criar tela no frontend com todos os componentes acordados no protótipo;
- [x] Integrar backend com frontend;
- [x] Criação de testes.

### Critérios de aceitação

- [x] Seguir o protótipo;
- [x] A tela mostrar todos os gados cadastrados até o momento no backend;
- [x] Testes funcionando.
