### ISSUE TITLE
Criação do documento de arquitetura

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#136]
## Descrição da Issue
Criação do corpo inicial do documento de arquitetura.

### Tasks: 
- [ ] Criar tópicos iniciais do documento de arquitetura.

### Critérios de aceitação

- [ ] Seguir o padrão da IBM;
- [ ] Todo o grupo concordar.

**Comment by ghost** [comment]
A issue ficou como dívida técnica.
