### ISSUE TITLE
US20 - Eu, como usuário, desejo selecionar o tipo de acasalamento realizado, para uma melhor organização dos meus manejos

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#138]
## Descrição da Issue
Eu, como usuário, desejo selecionar o tipo de acasalamento realizado para saber como foi gerado o bezerro de uma determinada vaca (inseminação, acasalamento, etc.).

### Tasks: 
- [ ] Colocar opção para selecionar o tipo de acasalamento;
- [ ] Elaborar função no backend e integrar com o frontend.

### Critérios de aceitação
- [ ] Integrar backend com o frontend;
- [ ] Estar tudo funcionando.
