### ISSUE TITLE
Documentar Fechamento da Sprint 9 e Abertura da Sprint 10

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#139]
## Descrição da Issue
Documentação do fechamento da sprint 9 e abertura da sprint 10.

### Tasks: 
- [x] Subir a documentação para o GitHub Pages;
- [x] Criar documento do fechamento da sprint 9 e abertura da sprint 10.

### Critérios de aceitação
- [x] Documento revisado e estar tudo certo;
- [x] Subir para o GitHub Pages.
