### ISSUE TITLE
US26 - Eu, como usuário, desejo cadastrar o peso do bovino, para ter o controle de ganho de massa do bovino

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#141]
# US26 - Eu, como usuário, desejo cadastrar o peso do bovino, para ter o controle de ganho de massa do bovino

## Descrição da Issue
Adição do campo de peso do bovino para fazer o manejo de pesagem.

### Tasks: 
- [x] Criação de tela de manejo;
- [x] Criação do campo de pesagem;
- [x] Criação do atributo pesagem no bovino no backend;
- [x] Salvar dado inserido.

### Critérios de aceitação
- [x] Ser fácil de usar;
- [x] Seguir protótipo;
- [x] Todo grupo validar.
