### ISSUE TITLE
Linkagem das telas dos bovinos

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#142]
# Linkagem das telas dos bovinos

## Descrição da Issue
Criar navegação entre as telas de criação e visualização de bovinos.

### Tasks: 
- [x] Associar geral de bovinos com a tela individual;
- [x] Associar a tela geral com a de criação;
- [x] Associar a tela de criação com a tela de visualização. 

### Critérios de aceitação
- [x] A navegação entre as telas estarem corretas;
- [ ] Todo o grupo aprovar.

**Comment by guilherme-mendes** [comment]
@sudjoao, se for possível ajustar o redirecionamento para tela geral dos bovinos ao confirmar o cadastro com sucesso dos bovinos na tela a seguir.
![image](https://user-images.githubusercontent.com/37874689/98168166-eb9a9100-1ec8-11eb-943b-b73ff1db5639.png)

**Comment by sudjoao** [comment]
Já  foi ajustado

**Comment by sudjoao** [comment]
Pull Request aceito, fechando  a issue.
