### ISSUE TITLE
Refatoração das páginas do frontend para aplicação de padrões de projeto

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#144]
# Refatoração das páginas do frontend

## Descrição da Issue
Refatorar código repetitivo no projeto utilizando padrões de projeto para reutilização de código.

### Tasks: 
- [X] Levantamento de páginas que podem ser reaproveitadas;
- [X] Levantamento de lógicas que podem ser raproveitadas;
- [X] Refatoração de páginas levantadas.

### Critérios de aceitação

- [X] Diminuir a repetição de código;
- [X] Telas continuarem funcionando;
- [X] Todo grupo concordar.
