### ISSUE TITLE
Documentar fechamento da Sprint 10 e aberturda da Sprint 11

### ISSUE THREAD

**Issue by caiovfernandes** [UnBArqDsw/2020.1_G13_iGado#149]
## Descrição da Issue
Documentação do fechamento da sprint 10 e abertura da sprint 11.

### Tasks: 
- [x] Subir a documentação para o GitHub Pages;
- [x] Criar documento do fechamento da sprint 10 e abertura da sprint 11.

### Critérios de aceitação
- [x] Documento revisado e estar tudo certo;
- [x] Subir para o GitHub Pages.
