### ISSUE TITLE
Atualizar Wiki para seguir a identidade visual do Projeto

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#15]
## Descrição da Issue
Atualizar visual da wiki de acordo com a identidade visual definida no protótipo.

### Tasks: 
- [x] Mudar cores na wiki;
- [x] Adicionar logo.

### Critérios de aceitação

- [x] Wiki seguir padrão visual;
- [x] Validação com o time.
