### ISSUE TITLE
Refatoração Backend

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#151]
# Refatoração do backend

## Descrição da Issue
Refatorar código repetitivo no projeto utilizando padrões de projeto para reutilização de código.

### Tasks: 
- [x] Levantamento de códigos que podem ser reaproveitados;
- [x] Levantamento de lógicas que podem ser reaproveitados;
- [x] Refatoração de códigos  levantados.

### Critérios de aceitação

- [x] Diminuir a repetição de código;
- [x] Telas continuarem funcionando;
- [x] Todo grupo concordar.
