### ISSUE TITLE
US38 - Relatorio GERAL

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#152]
### Tasks: 
- [x] Task 1
- [x] Task 2
- [x] Task 3

### Critérios de aceitação
- [x] Critério de aceitação 1
- [x] Critério de aceitação 2
- [x] Critério de aceitação 3
