### ISSUE TITLE
Documentar fechamento da Sprint 11 e aberturda da Sprint 12 

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#154]
## Descrição da Issue
Documentação do fechamento da sprint 11 e abertura da sprint 12.

### Tasks: 
- [x] Subir a documentação para o GitHub Pages;
- [x] Criar documento do fechamento da sprint 11 e abertura da sprint 12.

### Critérios de aceitação
- [x] Documento revisado e estar tudo certo;
- [x] Subir para o GitHub Pages.
