### ISSUE TITLE
Documentar Reutilizações de Software existentes no projeto

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#156]
## Descrição da Issue
Criar um documento explicitando a reutilização de software existente no projeto, desde os frameworks até bibliotecas importadas.

### Tasks: 
- [x] Documentar frameworks utilizados
- [x] Documentar bibliotecas utilizadas

### Critérios de aceitação
- [x] O documento deve conter informações sobre o Frontend e o Backend
- [x] O documento deve conter tabela de versionamento
- [x] O documento deve ser revisado por pelo menos um membro do grupo
