### ISSUE TITLE
Aplicar Autenticação JWT em todo o sistema.

### ISSUE THREAD

**Issue by caiovfernandes** [UnBArqDsw/2020.1_G13_iGado#158]
## Descrição da Issue
Avaliar todas as rotas, tanto do front quanto do back e definir quais delas precisam de autenticação.

#### Front End:
- [x] Salvar token
- [x] Configurar header com autenticação Bearer Token.
- [x] Refatorar todas as rotas que precisam ser autenticadas

#### Back End:
- [x] Enviar token ao front no Login
- [x] Refatorar todas as rotas que precisam validar a autenticação 

### Critérios de aceitação
- [x] Autenticação Funcionando no Front
- [x] Autenticação Funcionando no Back
