### ISSUE TITLE
Atualização dos documentos de padrões de projeto

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#160]
## Descrição da Issue
Atualizar documentos de padrões de projeto com os novos padrões aplicados.

### Tasks: 
- [ ] Adicionar padrão Strategy utilizado no frontend
- [x] Adicionar nova factory implementada para os manejos

### Critérios de aceitação
- [x] Documento possuir link para todos códigos de padrão de projeto

**Comment by sudjoao** [comment]
Acabei não documentando a parte de management como strategy pois não existe uma herança entre os 2 manejos
