### ISSUE TITLE
Integrar o Emoji-log ao script de commits

### ISSUE THREAD

**Issue by caiovfernandes** [UnBArqDsw/2020.1_G13_iGado#2]
## Descrição da Issue
Esta issue tem como objetivo integrar o log de commit [Emoji Log](https://github.com/ahmadawais/Emoji-Log) ao [Script](https://github.com/UnBArqDsw/2020.1_G13_Projeto/blob/master/commit) de **Política de commit**

### Tasks: 
- [x] Integrar o [Emoji Log](https://github.com/ahmadawais/Emoji-Log) ao fluxo de commits
- [x] Testar se caracteres de emoji funcionarão corretamente em diferentes terminais.

### Critérios de aceitação
- [x] [Script](https://github.com/UnBArqDsw/2020.1_G13_Projeto/blob/master/commit) com [Emoji Log](https://github.com/ahmadawais/Emoji-Log) funcionando corretamente com todos os membros.

**Comment by caiovfernandes** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42192251/91852019-9034f400-ec36-11ea-9d73-964a94faafd3.gif)
