### ISSUE TITLE
Elaborar Planejamento de Riscos e Plano de Comunicação

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#21]
## Descrição da Issue
Criação do documento de Planejamento de Riscos do projeto e Plano de Comunicação.

### Tasks: 
- [x] Identificar os riscos;
- [x] Adicionar as ferramentas de comunicação; 
- [x] Adicionar documento de Planejamento de Riscos e Plano de Comunicação na Wiki.

### Critérios de aceitação
- [x] Validar com os integrantes do grupo.

**Comment by ghost** [comment]
[Risk Management Plan.pdf](https://github.com/UnBArqDsw/2020.1_G13_Projeto/files/5196841/Riscos.pdf)
<img width="1232" alt="Risk Management Plan" src="https://user-images.githubusercontent.com/40740008/92630150-c4975880-f2a5-11ea-8dd9-dcbfb96f362c.png">
