### ISSUE TITLE
Documentar e explicar metodologia adotada

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#23]
## Descrição da Issue
Criar um documento detalhando a metodologia adotada pela equipe, seguindo as [Diretrizes de Entrega](https://aprender3.unb.br/pluginfile.php/26796/mod_assign/intro/Diretrizes%20-%20Entrega.pdf), tópico 1.2.

### Tasks: 
- [x] Detalhar metodologia adotada;
- [x] Referenciar metodologias bases;
- [x] Justificar escolhas dos princípios e das boas práticas.

### Critérios de aceitação
- [x] Documento deve ser validado com a equipe;
- [x] O documento deve possuir os rastro com a reunião na qual o grupo discutiu as metodologias.

**Comment by sudjoao** [comment]
<img width="884" alt="Screen Shot 2020-09-11 at 1 06 53 PM" src="https://user-images.githubusercontent.com/40740008/92948484-d3117b80-f42f-11ea-9dd0-b1d74e81ce77.png">
