### ISSUE TITLE
Elaborar BPMN

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#24]
## Descrição da Issue
Elaborar o documento _Business Process Management Notation_ (BPMN).

### Tasks: 
- [x] Criar o documento de BPMN;
- [x] Adicioná-lo na Wiki.

### Critérios de aceitação
- [x] Validar com os integrantes do grupo;
- [x] Verificar se atende aos conceitos de BPMN.

**Comment by sudjoao** [comment]
BPMN'S criados até o momento
![DesenvolverIdeiaDoProjeto](https://user-images.githubusercontent.com/46005310/92669367-b66a2c00-f2e7-11ea-8d88-e19daa223d84.png)
![MetodologiaGeral](https://user-images.githubusercontent.com/46005310/92669368-b702c280-f2e7-11ea-9684-23e27687f3fc.png)
![PlanejarSprint](https://user-images.githubusercontent.com/46005310/92669370-b79b5900-f2e7-11ea-94ee-09e6baacee6e.png)
![RealizarDesenvolvimentoDoProduto](https://user-images.githubusercontent.com/46005310/92669371-b833ef80-f2e7-11ea-8fdd-bad3cb4c846e.png)
![RealizarSprintReview](https://user-images.githubusercontent.com/46005310/92669372-b833ef80-f2e7-11ea-9b02-c93fabb59a1e.png)
![RealizarDesignSprint](https://user-images.githubusercontent.com/46005310/92669374-b8cc8600-f2e7-11ea-8842-43595b7a3bd9.png)
![RealizarPlanningPoker](https://user-images.githubusercontent.com/46005310/92669375-b8cc8600-f2e7-11ea-922f-b11d43f54049.png)
![RealizarSprintRetrospective](https://user-images.githubusercontent.com/46005310/92669376-b9651c80-f2e7-11ea-9451-e6173aead91d.png)

**Comment by sudjoao** [comment]
![Desenvolver Historias de Usuário](https://user-images.githubusercontent.com/46005310/92725109-ff4ece80-f341-11ea-92cb-c6392cacd4a5.png)
