### ISSUE TITLE
Elaborar léxicos 

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#26]
## Descrição da Issue
Elaborar documento de léxicos.

### Tasks:
- [x] Criar léxicos;
- [x] Adicioná-lo na Wiki.

### Critérios de aceitação
- [ ] Validar com os integrantes do grupo;
- [ ] Verificar se atende aos conceitos de léxicos.
