### ISSUE TITLE
Elaborar Políticas de Repositório

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#3]
## Descrição da Issue
Essa _issue_ é destinada a criação das políticas de repositório (issues, branches, commits e pull requests).

### Tasks: 
- [x] Elaboração da página de políticas do repositório;
- [x] Elaboração da política de issues;
- [x] Elaboração da política de branches;
- [x] Elaboração da política de commits;
- [x] Elaboração da política de pull requests.
