### ISSUE TITLE
Elaborar Backlog do Produto

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#31]
## Descrição da Issue
Elaborar Backlog do Produto.

### Tasks: 
- [x] Elaborar backlog do produto;
- [x] Adicionar na wiki.

### Critérios de aceitação
- [x] Validar com todos os integrantes do grupo;
- [x] Página com o backlog do produto.

**Comment by ghost** [comment]
Backlog realizado na reunião do dia 11/09/2020 envolvendo todos os integrantes do grupo.

<img width="706" alt="Screen Shot 2020-09-11 at 1 50 37 PM" src="https://user-images.githubusercontent.com/40740008/92952141-da3b8800-f435-11ea-85e2-3951132e75cf.png">
