### ISSUE TITLE
Documentar reuniões na Wiki

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#33]
## Descrição da Issue
Documentar reuniões que estão salvas na equipe do Teams no repositório e na wiki.

### Tasks: 
- [x] Criar modelo de ata de reunião, tanto para Sprint Planning quanto para Review e Retrospective
- [x] Transcrever reuniões documentadas no Teams seguindo o modelo
- [x] Adicionar reuniões na Wiki

### Critérios de aceitação
- [x] Todas reuniões estarem na Wiki, de forma organizada
- [x] Validar documentos com o time
