### ISSUE TITLE
Documentar Questionário na Wiki

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#36]
## Descrição da Issue
Documentar o questionário que foi criado para levantamento de requisitos e suas respostas.
### Tasks: 
- [x] Subir as perguntas;
- [x] Subir as respostas.

### Critérios de aceitação
- [x] Seguir padrão de outros documentos;
- [x] Validar com o grupo.

**Comment by sudjoao** [comment]
![Forms0](https://user-images.githubusercontent.com/46005310/92981374-e6dcd200-f46f-11ea-84e7-0e3e9ef9862a.png)
![Forms1](https://user-images.githubusercontent.com/46005310/92981376-e80dff00-f46f-11ea-9ec4-0a19be5e4bfd.png)
![Forms1](https://user-images.githubusercontent.com/46005310/92981378-e93f2c00-f46f-11ea-8fd0-e39e6f95e236.png)
![Forms2](https://user-images.githubusercontent.com/46005310/92981379-ea705900-f46f-11ea-9266-b6b13caea2b2.png)
![Forms3](https://user-images.githubusercontent.com/46005310/92981381-eba18600-f46f-11ea-9979-b7c1271e1c1d.png)
![Forms4](https://user-images.githubusercontent.com/46005310/92981384-ecd2b300-f46f-11ea-9771-46155cf6007b.png)
![Form5](https://user-images.githubusercontent.com/46005310/92981386-ee03e000-f46f-11ea-88b1-4dfd4f35fb52.png)

**Comment by sudjoao** [comment]
![image](https://user-images.githubusercontent.com/46005310/92981689-5bfcd700-f471-11ea-83c9-f824d65e25ce.png)
![image](https://user-images.githubusercontent.com/46005310/92981701-628b4e80-f471-11ea-84e9-4eefa8991f2c.png)
![image](https://user-images.githubusercontent.com/46005310/92981709-6b7c2000-f471-11ea-8ecd-284e4c787a4e.png)
![image](https://user-images.githubusercontent.com/46005310/92981717-76cf4b80-f471-11ea-89c8-014df7045231.png)
![image](https://user-images.githubusercontent.com/46005310/92981727-82227700-f471-11ea-97b6-f26ee150b16a.png)
![image](https://user-images.githubusercontent.com/46005310/92981732-8b134880-f471-11ea-8864-3bd705d7fa0f.png)
![image](https://user-images.githubusercontent.com/46005310/92981742-91a1c000-f471-11ea-8bb8-484887dd6a5e.png)
![image](https://user-images.githubusercontent.com/46005310/92981749-9bc3be80-f471-11ea-9b2d-e76fa377ad17.png)
