### ISSUE TITLE
Documentar entrevistas

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#39]
## Descrição da Issue
Documentar as entrevistas realizadas
### Tasks: 
- [x] Subir todos arquivos relacionados a entrevistas para wiki;

### Critérios de aceitação
- [x] Seguir padrão de outros documentos;
- [x] Validar com o grupo.
