### ISSUE TITLE
Elaborar documento de visão

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#4]
## Descrição da Issue
Elaboração do documento de visão para que haja um maior entendimento sobre o projeto.

### Tasks: 
- [x] Realizar a elaboração do documento de visão de acordo com o template da [IBM](https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html).

### Critérios de aceitação
- [ ] Todos os tópicos estejam preenchidos;
- [ ] Os tópicos devem seguir o modelo da IBM.

**Comment by caiovfernandes** [comment]
### Início de desenvolvimento do artefato
[Documento de visão.docx](https://teams.microsoft.com/l/file/3C92C901-C872-4629-B098-B179177D8F9C?tenantId=ec359ba1-630b-4d2b-b833-c8e6d48f8059&fileType=docx&objectUrl=https%3A%2F%2Funbbr.sharepoint.com%2Fsites%2FDesenho%2FDocumentos%20Compartilhados%2FGeneral%2FDocumento%20de%20Vis%C3%A3o%2FDocumento%20de%20visa%CC%83o2.docx&baseUrl=https%3A%2F%2Funbbr.sharepoint.com%2Fsites%2FDesenho&serviceName=teams&threadId=19:03a189f312844365926bcce3b98914f4@thread.tacv2&groupId=647c15bd-1003-4f40-b451-a41b75fa2230)
