### ISSUE TITLE
Elaboração Diagrama Entidade Relacionamento D-ER

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#44]
## Descrição da Issue
Elaborar o Diagrama Entidade Relacionamento (D-ER) para a modelagem do banco.

### Tasks: 
- [x] Elaborar Diagrama Entidade Relacionamento (D-ER);

### Critérios de aceitação
- [x] Validar com os integrantes do grupo;
- [x] Validar com os _stakeholders_;
- [x] Modelagem finalizada.

**Comment by ghost** [comment]
Pareamento com o @caiovfernandes para a elaboração do diagrama entidade relacionamento.
![diagrama_entidade_relacionamento](https://user-images.githubusercontent.com/40740008/93668808-7cc2bf00-fa65-11ea-9fe7-13a12154f587.png)
