### ISSUE TITLE
Fazer configuração inicial e padronização do repositório front-end 

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#46]
## Descrição da Issue
Fazer configuração inicial do repositório que o grupo irá utilizar para o front-end da aplicação.
### Tasks: 
- [x] Criação de novo repositório;
- [x] Pesquisar sobre padronização da linguagem;
- [x] Aplicar configuração e padronização escolhida;
- [x] Documentar instruções para rodar.

### Critérios de aceitação
- [x] O grupo concordar com a padronização e configuração;
- [x] Ter referência teórica que comprove que o modelo escolhido realmente é eficaz.

**Comment by sudjoao** [comment]
![image](https://user-images.githubusercontent.com/46005310/93666270-3fedcc80-fa53-11ea-96c8-a187c8771db8.png)

**Comment by sudjoao** [comment]
Flutter Extension VSCode
![image](https://user-images.githubusercontent.com/46005310/93666426-809a1580-fa54-11ea-84ad-1bac30a27c80.png)

**Comment by iurisevero** [comment]
Testei o repositório e tudo funcionou direito. Issue concluída
