### ISSUE TITLE
Fazer configuração inicial e padronização do repositório back-end

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#48]
## Descrição da Issue
Fazer configuração inicial do repositório que o grupo irá utilizar para o back-end da aplicação.
### Tasks: 
- [x] Criação de novo repositório;
- [x] Pesquisar sobre padronização da linguagem;
- [x] Aplicar configuração e padronização escolhida;
- [x] Documentar instruções para rodar.

### Critérios de aceitação
- [x] O grupo concordar com a padronização e configuração;
- [x] Ter referência teórica que comprove que o modelo escolhido realmente é eficaz.
