### ISSUE TITLE
Priorização Backlog

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#49]
## Descrição da Issue
Utilizar o MoSCoW para priorizar o backlog do produto.

### Tasks: 
- [x] Utilizar o MoSCoW para a priorização do backlog;
- [x] Adicionar na Wiki;

### Critérios de aceitação
- [x] Validar com os integrantes do grupo;
- [x] Adição do backlog priorizado na wiki;

**Comment by ghost** [comment]
Backlog priorizado na reunião de quarta-feira (16/09/2020) com a participação de todos.
<img width="584" alt="Screen Shot 2020-09-19 at 6 54 35 PM" src="https://user-images.githubusercontent.com/40740008/93689934-a998c580-faa9-11ea-86e2-3d928624bf68.png">
