### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#50]
## Descrição da Issue
Criação do Diagrama de Classes do Software iGado.

### Tasks: 
- [x] Levantamento de todas as classes envolvidas;
- [x] Levantamento dos atributos de cada classe;
- [x] Levantamento dos metodos de cada classe;
- [x] Fazer ligações entre as classes; 

### Critérios de aceitação
- [x] Validado por todo o grupo;
- [x] Seguir padrões bibliográficos.

**Comment by ghost** [comment]
Versão 0.5 do diagrama de classes.
![Diagrama de Classes iGado](https://user-images.githubusercontent.com/40740008/94342934-08e76000-ffeb-11ea-8cb3-5901572717c5.png)
