### ISSUE TITLE
Documentar fechamento da Sprint 3 e Abertura da Sprint 4

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#52]
## Descrição da Issue
Documentar as atas de fechamento e abertura das sprints 2 e 3, respectivamente.
### Tasks: 
- [ ] Documentar sprint Review;
- [ ] Documentar Sprint Retrospective
- [ ] Documentar Planning Poker;
- [ ] Documentar Sprint Planning.

### Critérios de aceitação
- [ ] Todos os ritos documentos;
- [ ] Documento seguindo o padrão criado.
