### ISSUE TITLE
Diagrama de Pacotes

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#54]
## Descrição da Issue
Criação do Diagrama de Pacotes do Software iGado.

### Tasks: 
- [x] Criação do diagrama de pacotes do backend;
- [x] Criação do diagrama de pacotes do frontend.

### Critérios de aceitação
- [x] Validado por todo o grupo;
- [x] Seguir padrões bibliográficos.

**Comment by guilherme-mendes** [comment]
## Diagrama de pacotes - Backend - Versão 1
![aaa](https://user-images.githubusercontent.com/37874689/93830043-7e4add80-fc45-11ea-9d19-4917b2d09540.png)

**Comment by guilherme-mendes** [comment]
## Diagrama de pacotes - Frontend - Versão 1
![aaa (2)](https://user-images.githubusercontent.com/37874689/93832375-e56b9080-fc4b-11ea-98bb-15596f40e6a8.png)

**Comment by guilherme-mendes** [comment]
/home/guiz/Documentos/desenho/2020.1_G13_Projeto/docs/Assets/Img/Modeling/DiagramPackage/PackageDiagramFrontV2.png

**Comment by guilherme-mendes** [comment]
![PackageDiagramFrontV2](https://user-images.githubusercontent.com/37874689/94033995-e0b3f300-fd97-11ea-83ca-d0f032958e05.png)

**Comment by sudjoao** [comment]
Pull request aprovado, fechando a issue.
