### ISSUE TITLE
Matriz de Relação

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#55]
## Descrição da Issue
Criação da Matriz de Relação.

### Tasks: 
- [x] Levantamento dos requisitos;
- [x] Correlacionar os requisitos levantados com as técnicas relacionadas.

### Critérios de aceitação
- [ ] Validado por todo o grupo;
- [ ] Seguir padrões bibliográficos.
