### ISSUE TITLE
Diagrama de Sequência

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#57]
## Descrição da Issue
Criação do Diagrama de Sequência do Software iGado

### Tasks: 
- [x] Definir módulos que serão criados
- [x] Criar um diagrama para cada módulo
- [x] Criar documento com diagramas na wiki

### Critérios de aceitação
- [x] Validado por todo o grupo;
- [x] Seguir padrões bibliográficos.

**Comment by iurisevero** [comment]
![SequenceDiagram-Registro e Login](https://user-images.githubusercontent.com/42645264/94064005-5ed7c000-fdbf-11ea-9032-0538dd638511.png)

**Comment by iurisevero** [comment]
![SequenceDiagram-Relatório](https://user-images.githubusercontent.com/42645264/94064021-65fece00-fdbf-11ea-9239-32987ab91ca5.png)

![SequenceDiagram-Relatório (1)](https://user-images.githubusercontent.com/42645264/94207175-6c637780-fe9d-11ea-974f-41b760d36e2d.png)

**Comment by iurisevero** [comment]
![Uploading SequenceDiagram-Cadastro de Bovino.png…]()

**Comment by iurisevero** [comment]
![SequenceDiagram-Cadastro de Bovino](https://user-images.githubusercontent.com/42645264/94064155-a1999800-fdbf-11ea-987f-101d6c21ff05.png)

![SequenceDiagram-Cadastro de Bovino (1)](https://user-images.githubusercontent.com/42645264/94207158-640b3c80-fe9d-11ea-94a5-44eb0081fedd.png)

**Comment by iurisevero** [comment]
![SequenceDiagram-Estoque de Insumos](https://user-images.githubusercontent.com/42645264/94207130-52299980-fe9d-11ea-8ebc-8a2bc0c8f5a3.png)

**Comment by iurisevero** [comment]
![SequenceDiagram-Manejo](https://user-images.githubusercontent.com/42645264/94207132-535ac680-fe9d-11ea-824e-26cc51760abc.png)
