### ISSUE TITLE
Diagrama de Componentes

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#64]
## Descrição da Issue
Criação do Diagrama de Componentes

### Tasks: 
- [x] Definir Subsistemas do projeto
- [x] Criar cada subsistema
- [x] Relacionar subsistemas

### Critérios de aceitação
- [ ] Validado por todo o grupo;
- [ ] Seguir padrões bibliográficos.

**Comment by iurisevero** [comment]
Rascunho do diagrama de componentes

![ComponentsDiagramDraft](https://user-images.githubusercontent.com/42645264/94380475-0e889700-010c-11eb-8bcf-04bfd3ce38ca.jpg)

**Comment by iurisevero** [comment]
![ComponentsDiagram](https://user-images.githubusercontent.com/42645264/94380482-15afa500-010c-11eb-9bd2-f142eea4ba3d.png)
