### ISSUE TITLE
Diagrama de Atividades

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#65]
## Descrição da Issue
Criação do diagrama de atividades para demonstrar os fluxos das atividades do software.

### Tasks: 
- [x] Criar diagramas de atividades.

### Critérios de aceitação
- [x] Seguir alguma referência bibliográfica;
- [x] Todas as atividades do projeto estarem representadas no diagrama.

**Comment by sudjoao** [comment]
![ManageCarters](https://user-images.githubusercontent.com/46005310/94374653-1fbdad80-00e4-11eb-9513-9a22a7c8cf62.png)
![ManageInputs](https://user-images.githubusercontent.com/46005310/94374656-20eeda80-00e4-11eb-9154-9fc846d260b4.png)
![Management](https://user-images.githubusercontent.com/46005310/94374657-20eeda80-00e4-11eb-97ef-23d95bed6480.png)
![MananeReport](https://user-images.githubusercontent.com/46005310/94374658-21877100-00e4-11eb-8f05-5be3bf9e61a4.png)
![Report](https://user-images.githubusercontent.com/46005310/94374659-22200780-00e4-11eb-95ef-47c8dd35344b.png)
![ShowCarters](https://user-images.githubusercontent.com/46005310/94374660-22200780-00e4-11eb-8e8b-6170b45cfd3b.png)
![ShowInputs](https://user-images.githubusercontent.com/46005310/94374662-22b89e00-00e4-11eb-814c-5782771bad95.png)
![SignInAndSignUp](https://user-images.githubusercontent.com/46005310/94374663-22b89e00-00e4-11eb-83c9-970a9ab38b2e.png)
