### ISSUE TITLE
Elaborar Diagrama de Estados

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#68]
## Descrição da Issue
Elaborar diagrama de estados.

### Tasks: 
- [ ] Elaborar diagrama de estados;
- [ ] Adicionar na wiki.

### Critérios de aceitação
- [ ] Validar com os integrantes do grupo.

**Comment by ghost** [comment]
Elaboração dos diagramas
![StateDiagram1](https://user-images.githubusercontent.com/40740008/94444904-349a4f80-017d-11eb-8196-459f5a93b866.png)

![StateDiagram2](https://user-images.githubusercontent.com/40740008/94444936-3f54e480-017d-11eb-8718-28c7b6326297.png)


![StateDiagram3](https://user-images.githubusercontent.com/40740008/94444944-424fd500-017d-11eb-9a4a-7dc153f21d7b.png)
