### ISSUE TITLE
Elaborar Rich Pictures

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#7]
## Descrição da Issue
Cada integrante do grupo deve elaborar uma rich picture.

### Tasks: 
- [x] Rich picture 1 - Lucas Fellipe Carvalho Moreira
- [x] Rich picture 2 - Iuri de Souza Severo Alves
- [x] Rich picture 3 - Guilherme Mendes Pereira
- [x] Rich picture 4 - Caio Vinícius Fernandes de Araújo
- [x] Rich picture 5 - João Pedro José Santos da Silva Guedes

**Comment by caiovfernandes** [comment]
![Caio - RichPicture v1](https://user-images.githubusercontent.com/42192251/91637816-751d7680-e9e1-11ea-9a26-e9417e3ef4db.jpg)

**Comment by lucasfcm9** [comment]
<img width="1206" alt="Screen Shot 2020-08-29 at 10 58 16 AM" src="https://user-images.githubusercontent.com/40740008/91638566-cd0aac00-e9e6-11ea-962a-595765238211.png">

**Comment by lucasfcm9** [comment]
<img width="1210" alt="Screen Shot 2020-08-29 at 11 01 08 AM" src="https://user-images.githubusercontent.com/40740008/91638589-f592a600-e9e6-11ea-8c20-2bde52b99744.png">

**Comment by ghost** [comment]
<img width="686" alt="Screen Shot 2020-08-29 at 11 38 44 AM" src="https://user-images.githubusercontent.com/40740008/91639339-3b05a200-e9ec-11ea-8b5b-82a842daae1a.png">

**Comment by guilherme-mendes** [comment]
![rich_picture_v1](https://user-images.githubusercontent.com/37874689/91639891-262b0d80-e9f0-11ea-8dcf-ae544872a4cc.png)

**Comment by iurisevero** [comment]
[iGado - RichPicture_v0.pdf](https://github.com/UnBArqDsw/2020.1_G13_Projeto/files/5145485/iGado.-.RichPicture_v0.pdf)
![iGado - RichPicture_v0](https://user-images.githubusercontent.com/42645264/91640741-32b26480-e9f6-11ea-9aaf-a21d00436c3c.jpeg)

**Comment by sudjoao** [comment]
![Johnson Rich Picture Atividades na Fazenda](https://user-images.githubusercontent.com/46005310/91641334-000a6b00-e9fa-11ea-8c0b-959f90982deb.jpg)

**Comment by guilherme-mendes** [comment]
Ótimo!
