### ISSUE TITLE
Refatorar documento de Léxicos

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#72]
## Descrição da Issue
Revisar léxicos e corrigir erros encontrados, conforme foi apontado na correção da primeira entrega do projeto.

### Tasks: 
- [ ] Revisar Léxicos
- [ ] Corrigir Léxicos que possuírem erro
- [ ] Atualizar documento na Wiki

### Critérios de aceitação
- [ ] Documento revisado pela equipe
- [ ] Os erros apontados no documento de resultado da primeira entrega estarem corrigidos
