### ISSUE TITLE
Refatoração de Documento de Design Sprint e seus artefatos

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#76]
## Descrição da Issue
Refatoração dos artefatos do design sprint de acordo com o feedback da professora.

### Tasks: 
- [x] Refatorar documento principal da metodologia design sprint;
- [x] Refatorar documentação do Brainstorming;
- [ ] Refatorar documentação do Mapa Mental;
- [ ] Refatorar documentação do Protótipo.

### Critérios de aceitação
- [ ] Resolver todas as observações deixadas pela professora;
- [ ] Aprovado pelo grupo;
- [ ] Utilizar pesquisas bibliográficas.

**Comment by sudjoao** [comment]
Telas Protótipo V1
![image](https://user-images.githubusercontent.com/46005310/94684850-03e22380-02ff-11eb-9343-9d3e038e6ad7.png)
