### ISSUE TITLE
Refatorar Plano de Custos

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#78]
## Descrição da Issue
Refatoração do Plano de Custos.

### Tasks: 
- [ ] Refatoração do plano de custos;
- [ ] Adicionar na Wiki.

### Critérios de aceitação
- [ ] Validar com os integrantes do grupo.
