### ISSUE TITLE
Dojo de Flutter

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#81]
## Descrição da Issue
Planejar e aplicar um treinamento sobre o conteúdo de flutter.

### Tasks: 
- [x] Planejar Treinamento;
- [x] Documentar planejamento;
- [x] Realizar dojo.

### Critérios de aceitação
- [x] O grupo participar do dojo;
- [x] O planejamento estar na wiki;
- [x] Abordar conteúdos básicos para entendimento da tecnologia.

**Comment by iurisevero** [comment]
Flutter Register Tree
![Dojo Flutter-Register](https://user-images.githubusercontent.com/42645264/95240567-faffbf00-07e2-11eb-8663-7fb12178e742.png)
Flutter Login Tree
![Dojo Flutter-Login](https://user-images.githubusercontent.com/42645264/95240574-fcc98280-07e2-11eb-973d-5515088ad12f.png)
Flutter Splash Tree
![Dojo Flutter-Splash](https://user-images.githubusercontent.com/42645264/95240576-fdfaaf80-07e2-11eb-979c-dd1bb8cea157.png)

**Comment by iurisevero** [comment]
![LoginScreenTree](https://user-images.githubusercontent.com/42645264/95507299-9893f380-0987-11eb-87ad-82e619c8401b.png)


![RegisterScreenTree](https://user-images.githubusercontent.com/42645264/95507305-99c52080-0987-11eb-807f-34d15a8e456e.png)


![SplashScreenTree](https://user-images.githubusercontent.com/42645264/95507307-9a5db700-0987-11eb-8832-62c0832b0597.png)
