### ISSUE TITLE
Estudo dirigido sobre padrões de projetos emergentes

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#82]
## Descrição da Issue
Estudar sobre padrões de projeto emergentes e documentar os estudos em um documento na Wiki.

### Tasks: 
- [x] Pesquisar padrões de projetos emergentes
- [x] Documentar dados analisados

### Critérios de aceitação
- [ ] O documento deve possuir tabela de versionamento
- [ ] O documento deve possuir referências
