### ISSUE TITLE
Estudo dirigido sobre GoFs Estruturais

### ISSUE THREAD

**Issue by ghost** [UnBArqDsw/2020.1_G13_iGado#83]
## Descrição da Issue
Elaborar um estudo dirigido sobre GoFs Estruturais e adicionar na Wiki para que os outros integrantes do grupo possam estudar por esse documento.

### Tasks: 
- [ ] Elaborar documento sobre GoFs Estruturais;
- [ ] Adicionar documento na Wiki.

### Critérios de aceitação
- [ ] Documento finalizado;
- [ ] Adicionar documento na wiki;
- [ ] Validar com os integrantes do grupo.

**Comment by ghost** [comment]
![Exemplo_do_padrão_adapter](https://user-images.githubusercontent.com/40740008/95642285-f276e500-0a7d-11eb-92f9-914cb8a2ebb8.jpg)

**Comment by ghost** [comment]
![ElementoGrafico](https://user-images.githubusercontent.com/40740008/95642694-88ac0a80-0a80-11eb-92f6-02a5e4fd61e0.jpg)

**Comment by ghost** [comment]
<img width="888" alt="Screen Shot 2020-10-10 at 12 17 46 PM" src="https://user-images.githubusercontent.com/40740008/95658693-b467d880-0af2-11eb-832f-c2a6c55373f5.png">

**Comment by ghost** [comment]
<img width="914" alt="Screen Shot 2020-10-10 at 12 21 01 PM" src="https://user-images.githubusercontent.com/40740008/95658753-19bbc980-0af3-11eb-88ed-4f396de3a49c.png">

**Comment by ghost** [comment]
<img width="824" alt="Screen Shot 2020-10-10 at 12 15 21 PM" src="https://user-images.githubusercontent.com/40740008/95658637-563af580-0af2-11eb-8822-b5515342fc72.png">

**Comment by ghost** [comment]
<img width="625" alt="Screen Shot 2020-10-10 at 12 33 22 PM" src="https://user-images.githubusercontent.com/40740008/95659021-d2363d00-0af4-11eb-8aa7-17a927538c2d.png">

**Comment by ghost** [comment]
<img width="967" alt="Screen Shot 2020-10-10 at 1 24 34 PM" src="https://user-images.githubusercontent.com/40740008/95660103-fcd7c400-0afb-11eb-84d7-34f4c95b38c2.png">

**Comment by ghost** [comment]
<img width="603" alt="Screen Shot 2020-10-10 at 1 27 12 PM" src="https://user-images.githubusercontent.com/40740008/95660157-53450280-0afc-11eb-8251-41378fbbecc3.png">

**Comment by ghost** [comment]
<img width="918" alt="Screen Shot 2020-10-10 at 1 39 40 PM" src="https://user-images.githubusercontent.com/40740008/95660406-11b55700-0afe-11eb-9fda-17e8572c504d.png">

**Comment by ghost** [comment]
<img width="593" alt="Screen Shot 2020-10-10 at 1 41 03 PM" src="https://user-images.githubusercontent.com/40740008/95660433-46291300-0afe-11eb-8b9c-6e7939937ff9.png">

**Comment by ghost** [comment]
<img width="974" alt="Screen Shot 2020-10-10 at 1 51 15 PM" src="https://user-images.githubusercontent.com/40740008/95660658-aff5ec80-0aff-11eb-9661-e325e481cc40.png">

**Comment by ghost** [comment]
![Screen Shot 2020-10-15 at 1 58 14 PM](https://user-images.githubusercontent.com/40740008/96162208-a3eaa000-0eee-11eb-9f79-b7c59a3b2657.png)

**Comment by ghost** [comment]
![Composite - Exemplo Extra](https://user-images.githubusercontent.com/40740008/96162609-1e1b2480-0eef-11eb-9725-1cbb945d8f1c.png)
