### ISSUE TITLE
Estudo dirigido sobre GRASP

### ISSUE THREAD

**Issue by caiovfernandes** [UnBArqDsw/2020.1_G13_iGado#85]
## Descrição da Issue
Elaborar um estudo dirigido sobre **GRASP** e adicionar na Wiki para que os outros integrantes do grupo possam estudar por esse documento.

### Tasks: 
- [ ] Elaborar documento sobre GRASP;
- [ ] Adicionar documento na Wiki.

### Critérios de aceitação
- [ ] Documento finalizado;
- [ ] Adicionar documento na wiki;
- [ ] Validar com os integrantes do grupo.
