### ISSUE TITLE
Estudo dirigido GoFs Comportamentais

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#86]
## Descrição da Issue
Elaborar um estudo dirigido sobre GoFs Comportamentais e adicionar na Wiki para que os outros integrantes do grupo possam estudar por esse documento.

### Tasks: 
- [ ] Elaborar documento sobre GoFs Comportamentais;
- [ ] Adicionar documento na Wiki.

### Critérios de aceitação
- [ ] Documento finalizado;
- [ ] Adicionar documento na wiki;
- [ ] Validar com os integrantes do grupo.
