### ISSUE TITLE
Estudo dirigido sobre GoFs Criacionais

### ISSUE THREAD

**Issue by guilherme-mendes** [UnBArqDsw/2020.1_G13_iGado#88]
## Descrição da Issue
Elaborar um estudo dirigido sobre GoFs Criacionais e adicionar na Wiki para que os outros integrantes do grupo possam estudar por esse documento.

### Tasks: 
- [ ] Elaborar documento sobre GoFs Comportamentais;
- [ ] Adicionar documento na Wiki.

### Critérios de aceitação
- [ ] Documento finalizado;
- [ ] Adicionar documento na wiki;
- [ ] Validar com os integrantes do grupo.
