### ISSUE TITLE
Database: Implementação do Data Definition Language do Banco de Dados

### ISSUE THREAD

**Issue by sudjoao** [UnBArqDsw/2020.1_G13_iGado#95]
## Descrição da Issue
Implementação do Data Definition Language do Banco de Dados, ou seja, criação dos comandos CREATE, ALTER e DROP.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criação de todas as models;
- [x] Criação dos métodos CREATE;
- [x] Criação dos métodos ALTER;
- [x] Criação dos métodos DROP;

### Critérios de aceitação

- [x] Seguir padrão estrutural definido pelo grupo, ou, caso existam alterações documentá-las;
- [x] Implementar todas as models;
- [x] Todo grupo concordar com o que foi feito.
