### ISSUE TITLE
Definir padrões dos GoF's Criacionais

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#97]
## Descrição da Issue
Explicar para a equipe o que é o padrão, a partir do estudo dirigido elaborado e, após a explicação, analisar com o grupo em quais partes do nosso projeto o padrão seria aplicável.

### Tasks: 
- [x] Explicar o que são os GoF's Criacionais
- [x] Analisar em quais partes do nosso projetos os GoF's Criacionais são aplicáveis
- [x] Criar um documento contendo o que foi discutido pelo grupo, se possível, com códigos do nosso projeto que seguem o padrão

### Critérios de aceitação
- [x] Documento com tabela de versão
- [x] Equipe revisou o documento
