### ISSUE TITLE
Definir padrões dos GoF's Comportamentais

### ISSUE THREAD

**Issue by iurisevero** [UnBArqDsw/2020.1_G13_iGado#99]
## Descrição da Issue
Explicar para a equipe o que é o padrão, a partir do estudo dirigido elaborado e, após a explicação, analisar com o grupo em quais partes do nosso projeto o padrão seria aplicável.

### Tasks: 
- [ ] Explicar o que são os GoF's Comportamentais
- [ ] Analisar em quais partes do nosso projetos os GoF's Comportamentais são aplicáveis
- [ ] Criar um documento contendo o que foi discutido pelo grupo, se possível, com códigos do nosso projeto que seguem o padrão

### Critérios de aceitação
- [ ] Documento com tabela de versão
- [ ] Equipe revisou o documento
